title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: Nighthawk Coders
github_username: nighthawkcoders
baseurl: "/student"
remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
title: [Manahil Khan]
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

